spring:
  application:
    name: 'gateway-service'

  cloud:
    kubernetes:
      reload:
        period: 1000
        enabled: true

zuul:
  routes:
    server-example:
      path: '/server/**'
      serviceId: 'server-example'
      url: 'http://server-example:8080/'
      sensitiveHeaders:
      stripPrefix: true