kind: Service
apiVersion: v1
metadata:
  name: server-example
spec:
  selector:
    app: server-example
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30084
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-example
spec:
  selector:
    matchLabels:
      app: server-example
  replicas: 1
  template:
    metadata:
      labels:
        app: server-example
    spec:
      containers:
        - name: server-example
          image: server-example
          imagePullPolicy: Never
          ports:
            - containerPort: 8080